services:
  - name: groq-telegram-bot
    type: web
    runtime: node
    buildCommand: pnpm install
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: Telegram
